version: "3.6"
services:
  im-client:
    build: ./im-client/
    container_name: im-client
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=im.godandanime.tv
      - VIRTUAL_PORT=8080
  im-server:
    build:
      context: ./im-server/
      dockerfile: ./IMWebAPI/Dockerfile
    container_name: im-server
    ports:
      - "5000:80"
  im-batch:
    build:
      context: ./im-server/
      dockerfile: ./BatchService/Dockerfile
    container_name: im-batch

networks:
  default:
    external:
      name: docker_default
